app/routes/admin_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from app.models import db, Company, CustomPlan, Employee, User

bp = Blueprint('admin_routes', __name__)

@bp.route('/admin/dashboard')
@login_required
def admin_dashboard():
    if not current_user.is_admin:
        return redirect(url_for('main_routes.home'))
    users = User.query.all()
    companies = Company.query.all()
    employees = Employee.query.all()
    return render_template('admin_dashboard.html', users=users, companies=companies, employees=employees)

@bp.route('/admin/create_company', methods=['GET', 'POST'])
@login_required
def create_company():
    if not current_user.is_admin:
        return redirect(url_for('main_routes.home'))
    if request.method == 'POST':
        name = request.form.get('name')
        user_limit = request.form.get('user_limit')
        token_limit = request.form.get('token_limit')
        new_company = Company(name=name, user_limit=user_limit, token_limit=token_limit)
        db.session.add(new_company)
        db.session.commit()
        flash('Company created successfully')
        return redirect(url_for('admin_routes.admin_dashboard'))
    return render_template('create_company.html')

@bp.route('/admin/create_custom_plan', methods=['GET', 'POST'])
@login_required
def create_custom_plan():
    if not current_user.is_admin:
        return redirect(url_for('main_routes.home'))
    if request.method == 'POST':
        company_id = request.form.get('company_id')
        price = request.form.get('price')
        tokens_per_user = request.form.get('tokens_per_user')
        new_plan = CustomPlan(company_id=company_id, price=price, tokens_per_user=tokens_per_user)
        db.session.add(new_plan)
        db.session.commit()
        flash('Custom plan created successfully')
        return redirect(url_for('admin_routes.admin_dashboard'))
    companies = Company.query.all()
    return render_template('create_custom_plan.html', companies=companies)

@bp.route('/admin/manage_company/<int:company_id>', methods=['GET', 'POST'])
@login_required
def manage_company(company_id):
    if not current_user.is_admin:
        flash('Acesso negado. Somente administradores podem acessar esta página.')
        return redirect(url_for('main_routes.home'))
    
    company = Company.query.get_or_404(company_id)
    return render_template('manage_company.html', company=company)

@bp.route('/admin/remove_employee/<int:employee_id>', methods=['POST'])
@login_required
def remove_employee(employee_id):
    employee = Employee.query.get_or_404(employee_id)
    if not current_user.is_admin:
        flash("Você não tem permissão para remover este empregado.")
        return redirect(url_for('main_routes.profile'))

    db.session.delete(employee)
    db.session.commit()
    flash("Empregado removido com sucesso.")
    return redirect(url_for('main_routes.profile'))

@bp.route('/admin/company/<int:company_id>/employees', methods=['GET', 'POST'])
@login_required
def manage_employees(company_id):
    company = Company.query.get_or_404(company_id)

    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        existing_employee = Employee.query.filter_by(email=email).first()
        if existing_employee:
            flash('Funcionário com este email já existe.')
        else:
            new_employee = Employee(name=name, email=email, company_id=company.id)
            db.session.add(new_employee)
            db.session.commit()
            flash('Funcionário adicionado com sucesso.')

    employees = Employee.query.filter_by(company_id=company_id).all()
    return render_template('manage_employees.html', company=company, employees=employees)

@bp.route('/admin/update_company/<int:company_id>', methods=['POST'])
@login_required
def update_company(company_id):
    if not current_user.is_admin:
        flash('Acesso negado. Somente administradores podem acessar esta página.')
        return redirect(url_for('main_routes.home'))
    
    company = Company.query.get_or_404(company_id)
    company.plan = request.form.get('plan')
    company.token_limit = request.form.get('token_limit')
    company.monthly_cost = request.form.get('monthly_cost')
    db.session.commit()
    
    flash('Empresa atualizada com sucesso.')
    return redirect(url_for('admin_routes.manage_company', company_id=company_id))

@bp.route('/admin/delete_company/<int:company_id>', methods=['POST'])
@login_required
def delete_company(company_id):
    if not current_user.is_admin:
        flash('Acesso negado. Somente administradores podem acessar esta página.')
        return redirect(url_for('main_routes.home'))
    
    company = Company.query.get_or_404(company_id)
    db.session.delete(company)
    db.session.commit()
    
    flash('Empresa deletada com sucesso.')
    return redirect(url_for('admin_routes.admin_dashboard'))

@bp.route('/admin/add_employee', methods=['POST'])
@login_required
def add_employee():
    if not current_user.is_admin:
        flash('Acesso negado. Somente administradores podem acessar esta página.')
        return redirect(url_for('main_routes.home'))

    name = request.form.get('name')
    email = request.form.get('email')
    company_id = request.form.get('company_id')
    existing_employee = Employee.query.filter_by(email=email).first()
    if existing_employee:
        flash('Funcionário com este email já existe.')
    else:
        new_employee = Employee(name=name, email=email, company_id=company_id)
        db.session.add(new_employee)
        db.session.commit()
        flash('Funcionário adicionado com sucesso.')

    return redirect(url_for('admin_routes.manage_employees', company_id=company_id))

app/routes/auth_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from app.models import db, User
from app.extensions import limiter
from datetime import datetime
import stripe
bp = Blueprint('auth', __name__)

@bp.route('/login', methods=['GET', 'POST'])
@limiter.limit("5 per minute")
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for('main_routes.chat'))
        else:
            flash('Login failed. Check your email and password.')
    return render_template('login.html')

@bp.route('/register', methods=['GET', 'POST'])
@limiter.limit("5 per minute")
def register():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        name = request.form.get('name')
        user = User(email=email, name=name, registration_date=datetime.utcnow())
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('main_routes.chat'))
    return render_template('register.html')

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    plan_names = {
        'free': 'Grátis',
        'standard': 'Padrão Mensal',
        'premium': 'Premium Mensal',
        'standard_annual': 'Padrão Anual',
        'premium_annual': 'Premium Anual'
    }
    plan_limits = {
        'free': 300,
        'standard': 5000,
        'premium': 10000,
        'standard_annual': 5000,
        'premium_annual': 10000
    }
    if request.method == 'POST':
        plan = request.form.get('plan')
        current_user.plan = plan
        db.session.commit()
        flash('Plano atualizado com sucesso.')
    return render_template('profile.html', plan_name=plan_names.get(current_user.plan, 'Grátis'), plan_limits=plan_limits)

@bp.route('/cancel_subscription', methods=['POST'])
@login_required
def cancel_subscription():
    if current_user.stripe_subscription_id:
        try:
            # Cancelar a assinatura
            subscription = stripe.Subscription.delete(current_user.stripe_subscription_id)
            print(f"Subscription status after deletion: {subscription['status']}")

            # Verificar se um reembolso é necessário
            if subscription['status'] == 'active':
                # Encontrar a última fatura paga
                invoices = stripe.Invoice.list(
                    subscription=current_user.stripe_subscription_id,
                    limit=1
                )
                print(f"Invoices found: {invoices['data']}")

                if invoices['data']:
                    last_invoice = invoices['data'][0]
                    print(f"Last invoice: {last_invoice}")

                    # Processar o reembolso
                    refund = stripe.Refund.create(
                        charge=last_invoice['charge']
                    )
                    print(f"Refund processed: {refund}")

            current_user.stripe_subscription_id = None
            current_user.plan = 'free'
            db.session.commit()
            print("User subscription and plan updated in database.")
            flash('Assinatura cancelada com sucesso e reembolso processado.')
            print('Assinatura cancelada com sucesso e reembolso processado.')
        except stripe.error.StripeError as e:
            print(f"Stripe error: {str(e)}")
            flash(f'Ocorreu um erro ao cancelar a assinatura: {str(e)}')
    else:
        print("User does not have a stripe_subscription_id.")
    return redirect(url_for('main_routes.profile'))

@bp.route('/remove_employee/<int:employee_id>', methods=['POST'])
@login_required
def remove_employee(employee_id):
    employee = User.query.get_or_404(employee_id)
    if current_user.company_id != employee.company_id:
        flash('Você não tem permissão para remover este empregado.')
        return redirect(url_for('main_routes.profile'))

    db.session.delete(employee)
    db.session.commit()
    flash('Empregado removido com sucesso.')
    return redirect(url_for('main_routes.profile'))

app/routes/main_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify, flash, current_app
from flask_login import login_required, current_user
from app.models import db, Company, User, FileContent, ChatMessage
import requests
import json
from app.extensions import limiter

bp = Blueprint('main_routes', __name__)

@bp.route('/')
def home():
    return render_template('index.html')

@bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    plan_names = {
        'free': 'Grátis',
        'standard': 'Padrão Mensal',
        'premium': 'Premium Mensal',
        'standard_annual': 'Padrão Anual',
        'premium_annual': 'Premium Anual',
        'unlimited': 'Ilimitado'  # Nome do plano ilimitado
    }
    plan_limits = {
        'free': 1500,
        'standard': 5000,
        'premium': 10000,
        'standard_annual': 5000,
        'premium_annual': 10000,
        'unlimited': float('inf')
    }
    if request.method == 'POST':
        plan = request.form.get('plan')
        current_user.plan = plan
        db.session.commit()
        flash('Plano atualizado com sucesso.')
    return render_template('profile.html', plan_name=plan_names.get(current_user.plan, 'Grátis'), plan_limits=plan_limits)

def get_context():
    context_records = FileContent.query.all()
    context = ""
    for record in context_records:
        context += f"\n{record.content[:1000]}"  # Limitar a quantidade de conteúdo para evitar excesso de tokens
    return context

@bp.route('/chat', methods=['GET', 'POST'])
@login_required
@limiter.limit("10 per minute")
def chat():
    if request.method == 'POST':
        user_message = request.json.get('message')

        # Definição do limite de tokens por plano
        plan_limits = {
            'free': 1500,
            'standard': 5000,
            'premium': 10000,
            'standard_annual': 5000,
            'premium_annual': 10000,
            'unlimited': float('inf')
        }

        # Verificação do plano do usuário ou da empresa
        if current_user.company_id:
            company = Company.query.get(current_user.company_id)
            if current_user.plan == 'unlimited':
                total_limit = float('inf')  # Limite ilimitado para o plano de empresa ilimitado
            else:
                total_limit = plan_limits.get(current_user.plan, 0) + company.token_limit
            token_usage = company.current_token_usage
        else:
            if current_user.plan == 'unlimited':
                total_limit = float('inf')
            else:
                total_limit = plan_limits.get(current_user.plan, 0) + current_user.token_limit
            token_usage = current_user.token_usage

        if token_usage >= total_limit:
            return jsonify({"error": "Token limit exceeded for your plan."})

        # Acessar a API_KEY do aplicativo Flask
        api_key = current_app.config['API_KEY']
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }

        # Adicionar contexto à mensagem do usuário
        context = get_context()
        prompt = f"{context}\n\nUser: {user_message}\nAssistant:"

        # Corpo da mensagem
        body_msg = {
            "model": "gpt-4o-mini",
            "messages": [
                {"role": """system", "content": "Você é um psicólogo experiente especializado em Comunicação Não Violenta (CNV). Sua abordagem é sempre respeitosa e você tem o cuidado de entender e validar as experiências do paciente antes de responder. Aqui estão algumas diretrizes para suas respostas:

                    Respeito ao Paciente: Sempre trate o paciente com respeito e sensibilidade, considerando seus sentimentos e perspectivas.

                    Perguntar Antes de Responder: Antes de oferecer respostas ou conselhos, faça perguntas para entender melhor a situação e as necessidades do paciente.

                    Explicações Claras e Simples: Explique conceitos de CNV de forma clara e simples, como se estivesse ensinando a alguém que nunca ouviu falar sobre o assunto.

                    Uso de CNV em Conversas: Demonstre o uso da CNV em suas respostas, modelando como a linguagem pode ser utilizada de forma não violenta e empática.

                    Validação e Empatia: Valide os sentimentos do paciente e mostre empatia, reconhecendo suas experiências e emoções.

                    Orientação para Ação: Quando apropriado, ofereça orientações ou sugestões de ação baseadas nos princípios da CNV, sempre perguntando se o paciente está confortável com isso."""},
                {"role": "user", "content": prompt}
            ],
            "max_tokens": 138
        }

        link = 'https://api.openai.com/v1/chat/completions'
        # Enviando a requisição para a API da OpenAI
        req = requests.post(link, headers=headers, data=json.dumps(body_msg))

        # Verificando a resposta
        if req.status_code == 200:
            response = req.json()
            response_message = response['choices'][0]['message']['content']

            # Salvando a mensagem do usuário e a resposta do assistente no banco de dados
            user_chat = ChatMessage(user_id=current_user.id, role='user', content=user_message)
            assistant_chat = ChatMessage(user_id=current_user.id, role='assistant', content=response_message)
            db.session.add(user_chat)
            db.session.add(assistant_chat)
            db.session.commit()

            # Atualizando o uso de tokens do usuário ou da empresa
            token_count = sum(len(message['content']) for message in body_msg['messages'])
            if current_user.company_id:
                company.current_token_usage += token_count
                db.session.commit()
            else:
                current_user.token_usage += token_count
                db.session.commit()

            return jsonify({"response": response_message})
        else:
            return jsonify({"error": "Erro na requisição"}), req.status_code
    else:
        return render_template('chat.html')
@bp.route('/plans')
@login_required
def plans():
    return render_template('plans.html')


@bp.route('/chat/history', methods=['GET'])
@login_required
def chat_history():
    messages = ChatMessage.query.filter_by(user_id=current_user.id).all()
    chat_history = [{"role": msg.role, "content": msg.content} for msg in messages]
    return jsonify({"messages": chat_history})


@bp.route('/chat/clear', methods=['POST'])
@login_required
def clear_chat_history():
    ChatMessage.query.filter_by(user_id=current_user.id).delete()
    db.session.commit()
    return jsonify({"message": "Histórico de chat limpo com sucesso."})

app/templates/admin_dashboard.html
{% extends "base.html" %} {% block title %}Painel administrativo{% endblock %}
{% block content %}
<h1>Painel administrativo</h1>
<div class="container mt-5">
  <h3>Administar Usários</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>Email</th>
        <th>Plano</th>
        <th>Tokens Usados</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.plan }}</td>
        <td>{{ user.token_usage }}</td>
        <td>
          {% if user.stripe_subscription_id %}
          <form
            action="{{ url_for('admin_routes.admin_cancel_subscription', user_id=user.id) }}"
            method="post"
            style="display: inline"
          >
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button type="submit" class="btn btn-danger btn-sm">
              Cancelar Assinatura
            </button>
          </form>
          {% else %}
          <span>N/A</span>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<hr />
<table class="table">
  <h3>Administrar Empresas</h3>
  <thead>
    <tr>
      <th>Nome da Empresa</th>
      <th>Limite de Usuários</th>
      <th>Limite de Tokens</th>
      <th>Gerenciar</th>
      <th>Adcionar Funcionários</th>
    </tr>
  </thead>
  <tbody>
    {% for company in companies %}
    <tr>
      <td>{{ company.name }}</td>
      <td>{{ company.user_limit }}</td>
      <td>{{ company.token_limit }}</td>
      <td>
        <a
          href="{{ url_for('admin_routes.manage_company', company_id=company.id) }}"
          class="btn btn-sm btn-warning"
          >Gerenciar</a
        >
      </td>
      <td>
        <a
          href="{{ url_for('admin_routes.manage_employees', company_id=company.id) }}"
          class="btn btn-sm btn-success"
          >Adcionar Funcionários</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<hr />
<table class="table">
  <h3 class="mt-5">Funcionários Atuais</h3>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Tokens Usados</th>
    </tr>
  </thead>
  <tbody>
    {% for employee in employees %}
    <tr>
      <td>{{ employee.name }}</td>
      <td>{{ employee.email }}</td>
      <td>{{ employee.token_usage }}</td>
      <td>{{ employee.company_id }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
  </head>
  <body>
    <header class="bg-primary text-white p-3">
      <nav class="container">
        <ul class="nav">
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a
              class="nav-link text-white"
              href="{{ url_for('main_routes.chat') }}"
              >Chat</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link text-white"
              href="{{ url_for('main_routes.profile') }}"
              >Perfil</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link text-white"
              href="{{ url_for('main_routes.plans') }}"
              >Planos</a
            >
          </li>
          {% if current_user.is_admin %}
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle text-white"
              href="#"
              id="adminDropdown"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
              >Admin</a
            >
            <ul class="dropdown-menu" aria-labelledby="adminDropdown">
              <li>
                <a
                  class="dropdown-item"
                  href="{{ url_for('admin_routes.admin_dashboard') }}"
                  >Painel Admin</a
                >
              </li>
              <li>
                <a
                  class="dropdown-item"
                  href="{{ url_for('admin_routes.create_company') }}"
                  >Criar Empresa</a
                >
              </li>
              <li>
                <a
                  class="dropdown-item"
                  href="{{ url_for('admin_routes.create_custom_plan') }}"
                  >Criar Plano de Empresa</a
                >
              </li>
            </ul>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{{ url_for('auth.logout') }}"
              >Logout</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{{ url_for('auth.login') }}"
              >Login</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="{{ url_for('auth.register') }}"
              >Register</a
            >
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <div class="container mt-5">{% block content %}{% endblock %}</div>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
  </body>
</html>

app/templates/chat.html
{% extends "base.html" %} {% block title %}Chat{% endblock %} {% block content
%}
<div class="container mt-5">
  <h1 class="text-center mb-4">Chat</h1>
  <div id="chatbox" class="card">
    <div
      id="messages"
      class="card-body"
      style="height: 400px; overflow-y: auto"
    ></div>
    <div class="card-footer d-flex justify-content-between">
      <form
        id="chatForm"
        onsubmit="sendMessage(event)"
        class="d-flex flex-grow-1 me-2"
      >
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <input
          type="text"
          id="userInput"
          placeholder="Digite sua mensagem"
          class="form-control me-2"
          required
        />
        <button type="submit" id="sendButton" class="btn btn-primary">
          Enviar
        </button>
      </form>
      <button id="clearButton" class="btn btn-danger" onclick="clearChat()">
        Limpar Histórico
      </button>
    </div>
  </div>
</div>
<script src="{{ url_for('static', filename='js/chat.js') }}"></script>
{% endblock %}

app/templates/checkout.html
{% extends "base.html" %} {% block title %}Checkout{% endblock %} {% block
content %}
<form
  action="{{ url_for('stripe.subscribe') }}"
  method="post"
  id="payment-form"
>
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
  <div class="form-row">
    <label for="plan">Select Plan</label>
    <select name="plan_id" id="plan">
      <option value="plan_premium_monthly_id">Premium Monthly - $50</option>
      <option value="plan_standard_monthly_id">Standard Monthly - $30</option>
      <option value="plan_premium_annual_id">Premium Annual - $500</option>
      <option value="plan_standard_annual_id">Standard Annual - $300</option>
    </select>
  </div>
  <div class="form-row">
    <label for="card-element">Credit or debit card</label>
    <div id="card-element"></div>
    <div id="card-errors" role="alert"></div>
  </div>
  <button type="submit">Submit Payment</button>
  <input type="hidden" name="stripeToken" id="stripeToken" />
</form>
<script src="https://js.stripe.com/v3/"></script>
<script>
  var stripe = Stripe("{{ key }}");
  var elements = stripe.elements();
  var card = elements.create("card");
  card.mount("#card-element");

  card.addEventListener("change", function (event) {
    var displayError = document.getElementById("card-errors");
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = "";
    }
  });

  var form = document.getElementById("payment-form");
  form.addEventListener("submit", function (event) {
    event.preventDefault();

    stripe.createToken(card).then(function (result) {
      if (result.error) {
        var errorElement = document.getElementById("card-errors");
        errorElement.textContent = result.error.message;
      } else {
        stripeTokenHandler(result.token);
      }
    });
  });

  function stripeTokenHandler(token) {
    var hiddenInput = document.createElement("input");
    hiddenInput.setAttribute("type", "hidden");
    hiddenInput.setAttribute("name", "stripeToken");
    hiddenInput.setAttribute("value", token.id);
    form.appendChild(hiddenInput);
    form.submit();
  }
</script>
{% endblock %}

app/templates/create_company.html
{% extends "base.html" %} {% block title %}Criar Empresa{% endblock %} {% block
content %}
<h1>Criar Empresa</h1>
<form method="POST" action="{{ url_for('admin_routes.create_company') }}">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
  <div class="mb-3">
    <label for="name" class="form-label">Nome da Empresa</label>
    <input type="text" class="form-control" id="name" name="name" required />
  </div>
  <div class="mb-3">
    <label for="user_limit" class="form-label">Limite de Usuários</label>
    <input
      type="number"
      class="form-control"
      id="user_limit"
      name="user_limit"
      required
    />
  </div>
  <div class="mb-3">
    <label for="token_limit" class="form-label">Limite de Tokens</label>
    <input
      type="number"
      class="form-control"
      id="token_limit"
      name="token_limit"
      required
    />
  </div>

  <button type="submit" class="btn btn-primary">Criar</button>
</form>
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<a href="{{ url_for('auth.login') }}" class="btn btn-primary">Login</a>
{% endblock %}

app/templates/manage_employees.html
{% extends "base.html" %} {% block title %}Manage Employees{% endblock %} {%
block content %}
<h1>Gerenciar Funcionários</h1>
<div class="container mt-5">
  <h3>Adicionar Novo Funcionário</h3>
  <form method="POST" action="{{ url_for('admin_routes.add_employee') }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <div class="mb-3">
      <label for="name" class="form-label">Nome</label>
      
      <input type="text" class="form-control" id="name" name="name" required />
    </div>
    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        required
      />
    </div>
    <input type="hidden" name="company_id" value="{{ company.id }}" />
    <button type="submit" class="btn btn-primary">Adicionar Funcionário</button>
  </form>

  <hr />

  <h3>Funcionários Atuais</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Tokens Usados</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for employee in employees %}
      <tr>
        <td>{{ employee.name }}</td>
        <td>{{ employee.email }}</td>
        <td>{{ employee.token_usage }}</td>
        <td>
          <form
            method="POST"
            action="{{ url_for('admin_routes.remove_employee', employee_id=employee.id) }}"
            style="display: inline"
          >
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <button type="submit" class="btn btn-danger btn-sm">Remover</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %} {% block title %}Perfil{% endblock %} {% block content
%}
<div class="container mt-5">
  <h1>Perfil do Usuário</h1>
  <p>Email: {{ current_user.email }}</p>
  <p>Nome: {{ current_user.name }}</p>
  <p>Data de Registro: {{ current_user.registration_date }}</p>
  <p>Plano atual: {{ plan_name }}</p>
  <p>
    Limite de tokens: {{ current_user.token_limit +
    plan_limits.get(current_user.plan, 'Desconhecido') }}
  </p>
  <p>Tokens utilizados: {{ current_user.token_usage }}</p>
  {% if current_user.company %}
  <h2>Informações da Empresa</h2>
  <p>Empresa: {{ current_user.company.name }}</p>
  <p>
    Tokens utilizados pela empresa: {{ current_user.company.current_token_usage
    }}
  </p>
  <p>Limite de tokens da empresa: {{ current_user.company.token_limit }}</p>
  <h3>Empregados</h3>
  <ul>
    {% for employee in current_user.company.employees %}
    <li>{{ employee.name }} ({{ employee.email }})</li>
    {% endfor %}
  </ul>
  {% endif %} {% if current_user.plan != 'free' %}
  <form method="post" action="{{ url_for('auth.cancel_subscription') }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <button type="submit" class="btn btn-danger">Cancelar Assinatura</button>
  </form>
  {% endif %}
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %} {% block title %}Register{% endblock %} {% block
content %}
<div class="container mt-5">
  <h1>Register</h1>
  <form method="post" action="{{ url_for('auth.register') }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="mb-3">
      <label for="name" class="form-label">Name</label>
      <input type="text" class="form-control" id="name" name="name" required />
    </div>
    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        required
      />
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        required
      />
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
  </form>
</div>
{% endblock %}